add Privileges.app aliases for work

diff --git a/home/exact_dot_oh-my-zsh/exact_custom/00_custom.zsh.tmpl b/home/exact_dot_oh-my-zsh/exact_custom/00_custom.zsh.tmpl
--- a/home/exact_dot_oh-my-zsh/exact_custom/00_custom.zsh.tmpl
+++ b/home/exact_dot_oh-my-zsh/exact_custom/00_custom.zsh.tmpl
@@ -8,3 +8,26 @@ alias history="atuin history list"
 ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
 
 alias reload='exec env -i PATH=$PATH TERMINFO=$TERMINFO TERM=$TERM USER=$USER HOME=$HOME SHELL=$SHELL TMUX=$TMUX zsh --login'
+
+{{- if .work }}
+
+alias sudo="/Applications/Privileges.app/Contents/MacOS/PrivilegesCLI -a && /usr/bin/sudo"
+
+brew() {
+  local priv_commands=("install" "update" "upgrade" "uninstall" "cleanup" "reinstall" "doctor" "config")
+  if [[ " ${priv_commands[*]} " == *" $1 "* ]]; then
+    if [[ -t 1 ]]; then
+      if ! /usr/bin/groups | grep -q -E "\b(admin|wheel)\b"; then
+        if /Applications/Privileges.app/Contents/MacOS/PrivilegesCLI -a; then
+          sleep 1
+        else
+          /bin/echo "PrivilegesCLI failed to elevate. Aborting brew command." >&2
+          return 1
+        fi
+      fi
+    fi
+  fi
+  command brew "$@"
+  return $?
+}
+{{- end }}
